name: TravelPlanner
description: A sample web application
dependencies:
  angular: '>=0.12.0 <0.13.0'
  browser: any
  shadow_dom: any
  js: any
  angular_ui: any
  firebase: any
dependency_overrides:
  browser: any   
transformers:
- angular:
     html_files:
      - web/view/overview.html
      - web/view/add.html
      - lib/travelstep/travel_step_component.html
      